'''
Module with Pico-ICE pin definitions
'''
ICE_SPI_RX_PIN = 8
ICE_CRAM_CSN_PIN = 9
ICE_FLASH_CSN_PIN = 9
ICE_SPI_SCK_PIN = 10
ICE_SPI_TX_PIN = 11
ICE_FPGA_RGB0_PIN = 12
ICE_FPGA_RGB1_PIN = 15
ICE_FPGA_RGB2_PIN = 13
ICE_FPGA_CLOCK_PIN = 24
ICE_FPGA_CDONE_PIN = 26
ICE_FPGA_CRESET_B_PIN = 27
